name: CosmeticPerks
version: '${project.version}'
main: me.wesleynichols.cosmeticperks.CosmeticPerks
api-version: 1.19
authors: [ WesleyNichols, TheSheepGoesBa ]
description: Cosmetic additions for server donors
commands:
  cosmetic:
    description: Access the cosmetic menu
    usage: /cosmetic
    aliases: [trail. trails]
  limitedtrail:
    description: Grant or revoke limited trails
    usage: /limitedtrail <grant|revoke> <player> <elytra|player|projectile> <trail name>
    permission: cosmeticperks.limitedtrail
  reload:
    description: Reload plugin configs
    usage: /cosmeticperks:reload
    permission: cosmeticperks.reload
  shop:
    description: Redirects to the online store
    usage: /shop
    aliases: [store, buy, donate]