name: CosmeticPerks
version: '${project.version}'
main: cosmetic.perks.cosmeticperks.CosmeticPerks
api-version: 1.19
authors: [ WesleyNichols, TheSheepGoesBa ]
description: Perks for donators
commands:
  cosmetic:
    description: Access the cosmetic menu
    usage: /cosmetic
    permission: cosmeticperks.cosmetic