name: CosmeticPerks
version: '${project.version}'
depend: [AdvancedVanish]
main: cosmetic.perks.cosmeticperks.CosmeticPerks
api-version: 1.19
authors: [ WesleyNichols, TheSheepGoesBa ]
description: Perks for donors
commands:
  cosmetic:
    description: Access the cosmetic menu
    usage: /cosmetic
    permission: cosmeticperks.cosmetic
  sheep:
    description: Test GUI
    usage: /sheep
    permission: cosmeticperks.sheep