name: CosmeticPerks
version: '${project.version}'
depend: [AdvancedVanish]
main: cosmetic.perks.cosmeticperks.CosmeticPerks
api-version: 1.19
authors: [ WesleyNichols, TheSheepGoesBa ]
description: Perks for donors
commands:
  cosmetic:
    description: Access the cosmetic menu
    usage: /cosmetic
    aliases: [cosmetics, flare, style, custom, customize, accessory, trail, trails]
  shop:
    description: Prompt user to visit Shop page
    usage: /shop
    aliases: [shops, store, stores, buy, donate, donation, donations, donator, donators, donor, donors, purchase]